services:

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"


  artist-service:
    build: ./artist-service
    ports:
      - "8084:8084"


  playlist-service:
    build: ./playlist-service
    ports:
      - "8083:8083"

  song-service:
    build: ./song-service
    ports:
      - "8082:8082"
