version: '3.9'
services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
  artist-service:
    build: ./artist-service
    ports:
      - "8084:8080"
  playlist-service:
    build: ./playlist-service
    ports:
      - "8083:8080"
  song-service:
    build: ./song-service
    ports:
      - "8082:8080"
